"""initialize db

Revision ID: 210a9e3a065d
Revises: 
Create Date: 2023-10-04 18:31:03.057600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210a9e3a065d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_boys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crewmembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('best_boy_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['best_boy_id'], ['best_boys.id'], name=op.f('fk_crewmembers_best_boy_id_best_boys')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('best_boy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['best_boy_id'], ['best_boys.id'], name=op.f('fk_productions_best_boy_id_best_boys')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shootdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.DateTime(), nullable=True),
    sa.Column('crew_size', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_shootdays_production_id_productions')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shootday_id', sa.Integer(), nullable=True),
    sa.Column('crewmember_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('lunch_start', sa.Integer(), nullable=True),
    sa.Column('lunch_end', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('additional_terms', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crewmember_id'], ['crewmembers.id'], name=op.f('fk_workdays_crewmember_id_crewmembers')),
    sa.ForeignKeyConstraint(['shootday_id'], ['shootdays.id'], name=op.f('fk_workdays_shootday_id_shootdays')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workdays')
    op.drop_table('shootdays')
    op.drop_table('productions')
    op.drop_table('crewmembers')
    op.drop_table('best_boys')
    # ### end Alembic commands ###
