"""adds email column to best boy table and removes crew size from shootday

Revision ID: 364bbb50a8b6
Revises: 3f29de2c4c6a
Create Date: 2023-10-05 16:59:14.115146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364bbb50a8b6'
down_revision = '3f29de2c4c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('best_boys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    with op.batch_alter_table('shootdays', schema=None) as batch_op:
        batch_op.drop_column('crew_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shootdays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crew_size', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('best_boys', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
