"""adds core crew model to add core crew to project

Revision ID: 6132f9d6c5b7
Revises: 830e13662000
Create Date: 2023-10-16 08:49:33.148466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6132f9d6c5b7'
down_revision = '830e13662000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_roles',
    sa.Column('crewmember_id', sa.Integer(), nullable=True),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crewmember_id'], ['crewmembers.id'], name=op.f('fk_core_roles_crewmember_id_crewmembers')),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_core_roles_production_id_productions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_roles')
    # ### end Alembic commands ###
