"""adds unique constraint to core role

Revision ID: 61a78d27d01c
Revises: 9df0cac6a10b
Create Date: 2023-10-16 10:43:44.057209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a78d27d01c'
down_revision = '9df0cac6a10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_roles', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint('unique-core-role', ['production_id', 'crewmember_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_roles', schema=None) as batch_op:
        batch_op.drop_constraint('unique-core-role', type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
