"""fixes core role table

Revision ID: cbf172ba2d9e
Revises: 6132f9d6c5b7
Create Date: 2023-10-16 08:51:43.069523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf172ba2d9e'
down_revision = '6132f9d6c5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_role',
    sa.Column('crewmember_id', sa.Integer(), nullable=True),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crewmember_id'], ['crewmembers.id'], name=op.f('fk_core_role_crewmember_id_crewmembers')),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_core_role_production_id_productions'))
    )
    op.drop_table('core_roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_roles',
    sa.Column('crewmember_id', sa.INTEGER(), nullable=True),
    sa.Column('production_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['crewmember_id'], ['crewmembers.id'], name='fk_core_roles_crewmember_id_crewmembers'),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name='fk_core_roles_production_id_productions')
    )
    op.drop_table('core_role')
    # ### end Alembic commands ###
