"""adds core role as model

Revision ID: f502565d8f3e
Revises: cbf172ba2d9e
Create Date: 2023-10-16 09:10:13.635759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f502565d8f3e'
down_revision = 'cbf172ba2d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.Column('crewmember_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crewmember_id'], ['crewmembers.id'], name=op.f('fk_core_roles_crewmember_id_crewmembers')),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_core_roles_production_id_productions')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('core_role')
    with op.batch_alter_table('best_boys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('shootdays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shootdays', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('best_boys', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.create_table('core_role',
    sa.Column('crewmember_id', sa.INTEGER(), nullable=True),
    sa.Column('production_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['crewmember_id'], ['crewmembers.id'], name='fk_core_role_crewmember_id_crewmembers'),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name='fk_core_role_production_id_productions')
    )
    op.drop_table('core_roles')
    # ### end Alembic commands ###
